name = "cf-workers-telegram-bot-404-v2"
main = "packages/worker/src/index.ts"

workers_dev = true
compatibility_date = "2025-06-04"

[ai]
binding = "AI"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "llama3"
database_id = "f5dec19f-75df-4a7d-8f9c-bf6f5d17fdb9"

[[r2_buckets]]
binding = "R2"
bucket_name = "share3"
